---
title: "Testing GUIDE on other datasets"
output: html_notebook
---

Testing GUIDE with the baseball data
```{r}
u_guideDataPath = "data/GUIDE data/"
u_guideDataFile = "bbdat.txt"
u_guideDescFile = "bbdsc.txt"
u_outputPath    = "output/GUIDE test baseball"
```


Initialising
```{r}
# Loading libraries
library(dplyr)
library(tidyr)
library(guidr)
library(ggplot2)

# Create directories
treePath <- initpath(u_outputPath)
dir.create(treePath$outPath, recursive = TRUE)
```


Reading in data (and variable definition)
```{r,echo=TRUE}
p_data <- read.table(file.path(u_guideDataPath, u_guideDataFile), header = FALSE)
p_desc <- readLines(file.path(u_guideDataPath, u_guideDescFile))

p_desc <- data.frame(tmp=p_desc[4:length(p_desc)]) %>% 
  separate(tmp, into=c("id", "variable", "type"), sep=" ") %>% 
  mutate(factor=1.0) %>% 
  mutate(transform = "") %>% 
  mutate(demean = FALSE) %>% 
  mutate(firstdiff = FALSE)

names(p_data) <- p_desc$variable

head(p_desc)
head(p_data)

ggplot(p_data) +geom_point(aes(x=Bat86, y=Salary))
ggplot(p_data) +geom_point(aes(x=Hit86, y=Salary))

ggplot(p_data) +geom_point(aes(x=Bat86, y=Logsalary))
ggplot(p_data) +geom_point(aes(x=Hit86, y=Logsalary))

ggplot(p_data) + geom_point(aes(x=Bat86, y=Hit86, color=Logsalary, fill=Logsalary))
ggplot(p_data) + geom_point(aes(x=Bat86, y=Hit86, color=Salary, fill=Salary))
```

Prepare data and run GUIDE
```{r}
treeOpts <- initTreeOptions(prune      = "1",  # 1=prune by CV, 2=no pruning
                            nbcv       = 10,   # Number of cross-validation steps (i.e. number of sub data spaces)
                            cvtype     = "1",  # 1=mean-based CV tree, 2=median-based CV tree
                            sevalue    = 0.5,  # Standard Error number for pruning [0..1]
                            search     = "2",  # 1=split point from quantiles, 2=use exhaustive search
                            splitfrac  = NA,   # default splitting fraction (i.e. frac, where #splits = max(9,fract*n), with n = #cases in node)
                            truncmeth  = "3",  # Data truncation method (0=none, 1=node range, 2=+10% node range, 3=global range (default))
                            missregval = "2",  # Missing regressor values: 1=separate models, 2=impute with means (default), 3=constant model
                            maxsplits  = 6,    # max. no. split levels
                            minnbnodes = 3)    # min. node sample size 

v_data <- generate_input(p_data, p_desc, 
                         "Single tree > LMS - Multilinear", treeOpts, treePath, i_idcolumns=c("Id", "Name"))

run(treePath)
```

Processing GUIDE results
```{r}
v_tree    <- parse_output(file.path(u_outputPath, "GUIDEfile_out.txt"))
v_alloc   <- allocateDataToNodes(p_data, v_tree) 
v_regdata <- parse_regcoef(regfile)
```


Plotting GUIDE results
```{r}
plot_tree(v_tree, 
                TITLE=paste0("RT - LMS-Multilinear\n Tn:", length(which(v_tree$nodeType == "Terminal node"))), 
                CEX=NULL, LEGEND.X = 0, LEGEND.Y = 1.1, LEGEND.CEX=0.5, LEGEND.NCOL=2)
```


