---
title: "Testing GUIDE on other datasets"
output: html_notebook
---

Testing GUIDE with the wage data (longitudinal data)
```{r}
u_guideDataPath = "data/GUIDE data/"
u_guideDataFile = "wagedat.txt"
u_guideDescFile = "wagedsc.txt"
u_outputPath    = "output/GUIDE test wage"
```


Initialising
```{r}
# Loading libraries
library(dplyr)
library(tidyr)
library(guidr)
library(ggplot2)

# Create directories
treePath <- initpath(u_outputPath)
dir.create(treePath$outPath, recursive = TRUE)
```


Reading in data (and variable definition)
```{r,echo=TRUE}
p_desc <- readLines(file.path(u_guideDataPath, u_guideDescFile))
p_desc <- data.frame(tmp=p_desc[4:length(p_desc)]) %>% 
  separate(tmp, into=c("id", "variable", "type"), sep=" ") %>% 
  mutate(factor=1.0) %>% 
  mutate(transform = "") %>% 
  mutate(demean = FALSE) %>% 
  mutate(firstdiff = FALSE)

p_data <- read.table(file.path(u_guideDataPath, u_guideDataFile), header = FALSE, col.names = p_desc$variable)

head(p_desc)
head(p_data)


#ggplot(p_data) +geom_point(aes(x=age, y=weight))
#ggplot(p_data) +geom_point(aes(x=black, y=weight))
# 
# ggplot(p_data) + geom_point(aes(x=Bat86, y=Hit86, color=Logsalary, fill=Logsalary))
# ggplot(p_data) + geom_point(aes(x=Bat86, y=Hit86, color=Salary, fill=Salary))
```

Prepare data and run GUIDE
```{r}
treeOpts <- initTreeOptions(prune      = "1",  # 1=prune by CV, 2=no pruning
                            nbcv       = 10,   # Number of cross-validation steps (i.e. number of sub data spaces)
                            cvtype     = "1",  # 1=mean-based CV tree, 2=median-based CV tree
                            sevalue    = 0.0,  # Standard Error number for pruning [0..1]
                            search     = "2",  # 1=split point from quantiles, 2=use exhaustive search
                            splitfrac  = NA,   # default splitting fraction (i.e. frac, where #splits = max(9,fract*n), with n = #cases in node)
                            truncmeth  = "3",  # Data truncation method (0=none, 1=node range, 2=+10% node range, 3=global range (default))
                            missregval = "2",  # Missing regressor values: 1=separate models, 2=impute with means (default), 3=constant model
                            maxsplits  = 10,   # max. no. split levels
                            minnbnodes = 44    # min. node sample size
                            )

if (length(which(p_desc$variable == "id")) == 0) {
  p_desc <- p_desc %>% 
    add_row(id=12, variable="id", type="x", factor=1, transform="", demean=FALSE, firstdiff=FALSE)
}

ncases = 1

p_desc_mod <- p_desc
# postexp, ged, uerate
p_desc_mod$type[grep("postexp", p_desc_mod$variable)] <- "t"

v_data     <- list()
v_dataProc <- list()
v_tree     <- list()
v_alloc    <- list()

dir.create(file.path(u_outputPath, "GUIDE results", "output"), recursive = TRUE)

for (k in 1:ncases) {
  
  if (k == 1) {
    v_data[[k]] <- p_data #cbind(data.frame(id=1:dim(p_data)[1]), p_data)
  } else {
    if (k <= 20) {
      idsel = sample(nrow(p_data), nrow(p_data)*0.99) # select 99% of the data randomly
      v_data[[k]] <- cbind(data.frame(id=idsel), p_data[idsel,]) }
    else {
      if (k <= 40) {
        idsel = sample(nrow(p_data), nrow(p_data)*0.99) # select 99% of the data randomly
        v_data[[k]] <- cbind(data.frame(id=idsel), p_data[idsel,]) }
      else {
        idsel = sample(nrow(p_data), nrow(p_data)-1) # Remove one data point randomly
        v_data[[k]] <- cbind(data.frame(id=idsel), p_data[idsel,])
      }
    }
  }
  
    
  treePath <- initpath(file.path(u_outputPath, "GUIDE results", paste0(u_outputPath, " - case", k)))

  v_dataProc[[k]] <- generate_input(v_data[[1]], p_desc_mod, 
                                    "Single tree > Longitudinal - Lowess smoothing", treeOpts, treePath)
  
  run(treePath)
  
  v_tree[[k]]    <- parse_output(file.path(treePath$outPath, "GUIDEfile_out.txt"), p_desc_mod)
  v_alloc[[k]]   <- allocateDataToNodes(v_dataProc[[k]], v_tree[[k]]) 

}


```

Saving results
```{r}
save(v_data, v_DataProc, v_tree, v_alloc, v_regdata, file = file.path(u_outputPath, "data", paste0("guide_test_wage_", ncases, "cases.pdf")))
```



Plotting GUIDE results
```{r}
for (k in 1:ncases) {
  print(paste0("case ", k))
  plot_tree(v_tree[[k]], 
                  TITLE=paste0("R-Tree ", k, "\n Tn:", length(which(v_tree[[k]]$nodeType == "Terminal node"))), 
                  CEX=NULL, LEGEND.X = 0, LEGEND.Y = 1.1, LEGEND.CEX=0.5, LEGEND.NCOL=2, YESNO=TRUE)
  plot_tree(v_tree[[k]], 
                  TITLE=paste0("R-Tree ", k, "\n Tn:", length(which(v_tree[[k]]$nodeType == "Terminal node"))), 
                  CEX=NULL, LEGEND.X = 0, LEGEND.Y = 1.1, LEGEND.CEX=0.5, LEGEND.NCOL=2, YESNO=TRUE,
                FILENAME = file.path(file.path(u_outputPath, "plots", paste0("RTree_", ifelse(k<10, paste0("0",k), paste0(k)), ".pdf"))))
  plot_tree(v_tree[[k]], 
                  TITLE=paste0("R-Tree ", k, "\n Tn:", length(which(v_tree[[k]]$nodeType == "Terminal node"))), 
                  CEX=NULL, LEGEND.X = 0, LEGEND.Y = 1.1, LEGEND.CEX=0.5, LEGEND.NCOL=2, YESNO=TRUE,
                FILENAME = file.path(file.path(u_outputPath, "plots", paste0("RTree_", ifelse(k<10, paste0("0",k), paste0(k)), ".png"))))
}
```


```{r}
compare_trees <- function(kt1, kt2) {
  id1 = kt1
  id2 = kt2
    
  dfid1 <- unique(v_alloc[[id1]]$id)
  dfid2 <- unique(v_alloc[[id2]]$id)
  
  v_alloc1 <- v_alloc[[id1]] %>% filter(id %in% dfid2)
  v_alloc2 <- v_alloc[[id2]] %>% filter(id %in% dfid1)

  tmp <- v_tree[[id1]] %>% filter(nodeType == "Terminal node") %>% select(nodeID,n) %>% filter(nodeID %in% unique(v_alloc1$tnode)) %>% arrange(desc(n)) %>% mutate(levelsid1 = paste0(nodeID, " (", n, ")"))
  tNodeIDs1 <- tmp$nodeID
  levelsID1 <- tmp$levelsid1
  tmp <- v_tree[[id2]] %>% filter(nodeType == "Terminal node") %>% select(nodeID,n) %>% filter(nodeID %in% unique(v_alloc2$tnode)) %>% arrange(desc(n)) %>% mutate(levelsid2 = paste0(nodeID, " (", n, ")"))
  tNodeIDs2 <- tmp$nodeID
  levelsID2 <- tmp$levelsid2
  
    
  m_abs  <- matrix(NA, nrow = length(tNodeIDs1), ncol = length(tNodeIDs2))
  m_rel1 <- matrix(NA, nrow = length(tNodeIDs1), ncol = length(tNodeIDs2))
  m_rel2 <- matrix(NA, nrow = length(tNodeIDs1), ncol = length(tNodeIDs2))
  for (kr in 1:length(tNodeIDs1)) {
    id_dp1 <- which(v_alloc1$tnode == tNodeIDs1[kr])
    dp1 <- paste0(v_alloc1$id[id_dp1])
    nbdp1 <- length(dp1)
    alldp2 = c()
    for (kc in 1:length(tNodeIDs2)) {
      id_dp2 <- which(v_alloc2$tnode == tNodeIDs2[kc])
      dp2 <- paste0(v_alloc2$id[id_dp2])
      alldp2 <- c(alldp2, dp2)
      nbdp2 <- length(dp2)
      
      m_abs[kr,kc]  <- length(which(dp1 %in% dp2))
      m_rel1[kr,kc] <- length(which(dp1 %in% dp2))/nbdp1
      m_rel2[kr,kc] <- length(which(dp2 %in% dp1))/nbdp2
    } 
    
    missing_dp1 <- dp1[which(!dp1 %in% alldp2)]
    if (length(missing_dp1) != 0) {
      print(tNodeIDs1[kr])
      print(tNodeIDs2[kr])
      print(dp1)
      print(dp2)
      print(tNodeIDs1[kr])
      print(missing_dp1)
      stop()
    }
    
  }
  
  
  
  process_m <- function(m, id1, id2) {
    colnames(m) <- paste(tNodeIDs2)
    m <- round(m, digits = 2) %>% 
      as.data.frame() %>% 
      mutate(TN_T1=tNodeIDs1) %>% 
      gather(TN_T2, value, -TN_T1) %>% 
      left_join(v_tree[[id1]] %>% select(nodeID,n), by=c("TN_T1"="nodeID")) %>% 
      rename(n1=n) %>% 
      mutate(TN_T1=paste0(TN_T1," (", n1, ")")) %>% 
      left_join(v_tree[[id2]] %>% select(nodeID,n), by=c("TN_T2"="nodeID")) %>% 
      rename(n2=n) %>% 
      mutate(TN_T2=paste0(TN_T2," (", n2, ")")) %>% 
      mutate(TN_T1=factor(TN_T1, levels=levelsID1 ,ordered=TRUE)) %>% 
      mutate(TN_T2=factor(TN_T2, levels=levelsID2 ,ordered=TRUE))
  }
  
  
  m_abs <- process_m(m_abs, id1, id2) %>% 
    mutate(type=ifelse(value == 0, "zero", "nonzero"))
  m_rel1 <- process_m(m_rel1, id1, id2)
  m_rel2 <- process_m(m_rel2, id1, id2)
  m_rel <- left_join(
    m_rel1 %>% 
      rename(rel1=value),
    m_rel2 %>% 
      rename(rel2=value) %>% 
      select(-n1,-n2)
  ) %>% 
    mutate(value = n1/(n1+n2)*rel1 + n2/(n1+n2)*rel2) 
  
  misalloc <- round((m_abs %>% group_by(TN_T1) %>% filter(value != max(value)) %>% summarise(sum=sum(value)) %>% ungroup() %>% summarise(sum=sum(sum)))$sum/sum(m_abs$value)*100, digits=1)
  
  ggplot(m_rel) + 
    geom_tile(aes(x=TN_T2, y=TN_T1, fill=value)) + 
    geom_text(aes(x=TN_T2, y=TN_T1, label=value, colour=type), data=m_abs) +
    scale_fill_gradient(low = "#ffffff", high="#ff0000") +
    scale_color_manual(values=c("nonzero"="#000000", zero="#eeeeee")) +
    ylab(paste0(names(u_cases)[id1], " (", length(tNodeIDs1), ")")) + xlab(paste0(names(u_cases)[id2], " (", length(tNodeIDs2), ")")) +
    ggtitle(paste0("Misallocation (%): ", misalloc))
  
  return(misalloc)
}

m_comp  <- matrix(NA, nrow = ncases, ncol = ncases)
for (kt1 in 1:ncases) {
  for (kt2 in 1:ncases) {
    print(paste0(kt1, "-", kt2))
    m_comp[kt1, kt2] <- compare_trees(kt1, kt2)
  }
}



tmp <- m_comp

namenbtn <- do.call("rbind", lapply(1:ncases, function(x) data.frame(name=x, nbtn=length(unique(v_alloc[[x]]$tnode))))) %>%
  mutate(name = paste0(1:ncases))

colnames(tmp)  <- paste0(namenbtn$name, " (", namenbtn$nbtn, ")")
row.names(tmp) <- paste0(namenbtn$name, " (", namenbtn$nbtn, ")")

tmp <- tmp %>%
  as.data.frame() %>%
  mutate(T1 = factor(paste0(namenbtn$name, " (", namenbtn$nbtn, ")"), levels=paste0(namenbtn$name, " (", namenbtn$nbtn, ")"), ordered=TRUE)) %>% 
  gather(T2, value, -T1)  %>% 
  mutate(T2 = factor(T2, levels=paste0(namenbtn$name, " (", namenbtn$nbtn, ")"), ordered=TRUE))

# ggplot(tmp) + 
#   geom_tile(aes(x=T2, y=T1, fill=value)) + 
#   geom_text(aes(x=T2, y=T1, label=value)) +
#   scale_fill_gradient(low = "#ffffff", high="#ff0000") +
#   theme(axis.text.x = element_text(angle=90))

# 1% (500/50000)
ggplot(tmp %>% filter(grepl("^1[[:space::]|^[2-9][[:space:]]|^1[0-9]{1}|^20", T1), grepl("^1[[:space::]|^[2-9][[:space:]]|^1[1-9]{1}|^20", T2))) + 
    geom_tile(aes(x=T2, y=T1, fill=value)) + 
    geom_text(aes(x=T2, y=T1, label=value)) +
    scale_fill_gradient(low = "#ffffff", high="#ff0000") +
    theme(axis.text.x = element_text(angle=90)) +
    ggtitle("Random sample of 49500 out of 50000 observations (1%)")
ggsave(filename=file.path(u_outputPath, "plots", "TSM_1pct.pdf"), width=15, height=15)

# 0.1 %  (50/50000)
ggplot(tmp %>% filter(grepl("^1[[:space::]|^2[1-9]{1}|^3[0-9]{1}|^40", T1), grepl("^1[[:space::]|^2[1-9]{1}|^3[0-9]{1}|^40", T2))) + 
    geom_tile(aes(x=T2, y=T1, fill=value)) + 
    geom_text(aes(x=T2, y=T1, label=value)) +
    scale_fill_gradient(low = "#ffffff", high="#ff0000") +
    theme(axis.text.x = element_text(angle=90)) +
    ggtitle("Random sample of 49950 out of 50000 observations (0.1%)")
ggsave(filename=file.path(u_outputPath, "plots", "TSM_0.1pct.pdf"), width=15, height=15)

# 0.002% (1/50000)
ggplot(tmp %>% filter(grepl("^1[[:space::]|^4[1-9]{1}|^50", T1), grepl("^1[[:space::]|^4[1-9]{1}|^50", T2))) + 
    geom_tile(aes(x=T2, y=T1, fill=value)) + 
    geom_text(aes(x=T2, y=T1, label=value)) +
    scale_fill_gradient(low = "#ffffff", high="#ff0000") +
    theme(axis.text.x = element_text(angle=90)) +
    ggtitle("Random sample of 49999 out of 50000 observations (0.002%)")
ggsave(filename=file.path(u_outputPath, "plots", "TSM_0.002pct.pdf"), width=15, height=15)

```

Save tree similarity matrix
```{r}
save(m_comp, file = file.path(u_outputPath, "data", paste0("guide_test_birthwt_TSM_", ncases, "cases.pdf")))
```

Check distribution of root nodes
```{r}
tmp <- do.call("rbind", 
        lapply(1:ncases, function(x) data.frame(tree=x, 
                                                type=ifelse(x == 1,
                                                            "original", 
                                                            ifelse(x > 1 & x < 21,
                                                                   "1%",
                                                                   ifelse(x > 20 & x < 41,
                                                                          "0.1%", "0.002%"))),
                                                count=1, 
                                                rootnode=paste0(v_tree[[x]]$variable[which(v_tree[[x]]$nodeType == "Root node")[1]], "-", v_tree[[x]]$value[which(v_tree[[x]]$nodeType == "Root node")[1]]))))

ggplot(tmp) +
  geom_bar(aes(x=rootnode, y=count, fill=type), stat="identity")
ggsave(filename=file.path(u_outputPath, "plots", "Rootnodes2.pdf"), width=15, height=15)

tmp <- do.call("rbind", 
        lapply(1:ncases, function(x) {
          type <- ifelse(x == 1,
                          "original", 
                          ifelse(x > 1 & x < 21,
                                 "1%",
                                 ifelse(x > 20 & x < 41,
                                        "0.1%", "0.002%")))
          data.frame(tree = c(x, x), 
                     count     = c(1, 1),
                     type = c(type, type),
                     position  = c("left", "right"),
                     rootnode=paste0(v_tree[[x]]$variable[which(v_tree[[x]]$nodeType == "Root node")[1]], "-", v_tree[[x]]$value[which(v_tree[[x]]$nodeType == "Root node")[1]]),
                     nodepath = c(
                       paste0(v_tree[[x]]$variable[which(v_tree[[x]]$parentNodeID == 1)[1]], "-",v_tree[[x]]$value[which(v_tree[[x]]$parentNodeID == 1)[1]]),
                       paste0(v_tree[[x]]$variable[which(v_tree[[x]]$parentNodeID == 1)[2]], "-",v_tree[[x]]$value[which(v_tree[[x]]$parentNodeID == 1)[1]])))
          }))


ggplot(tmp) +
  geom_bar(aes(x=nodepath, y=count, fill=type), stat="identity") + facet_grid(rootnode~position, scales = "free_x") 
ggsave(filename=file.path(u_outputPath, "plots", "NodePaths2.pdf"), width=15, height=15)


```

